const langButtons=document.querySelectorAll('[data-lang]');
let lang=new URLSearchParams(location.search).get('lang'),page=0,rows=[],more=false,notice='',loading=false;
try{lang=lang||localStorage.getItem('scar-patte-language')||'fr'}catch{}
if(!bookingCopy[lang])lang='fr';
const ticketCopy={fr:{example:'Exemple fictif',kindness:'UN PEU DE DOUCEUR',owner:'Son humain',logout:'Déconnexion',dogNote:'Premier bain, brossage doux.',catNote:'Entretien du pelage, séance calme.'},en:{example:'Example booking',kindness:'A LITTLE KINDNESS',owner:'Their human',logout:'Sign out',dogNote:'First bath, gentle brushing.',catNote:'Coat maintenance, a calm session.'},nl:{example:'Voorbeeldaanvraag',kindness:'EEN BEETJE LIEFDE',owner:'Hun baasje',logout:'Afmelden',dogNote:'Eerste wasbeurt, voorzichtig borstelen.',catNote:'Vachtverzorging, een rustige sessie.'}};
const c=()=>bookingCopy[lang],t=()=>ticketCopy[lang];
const list=document.querySelector('#request-list'),states=['new','contacted','confirmed','closed'];
function el(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
const paper='<svg class="booking-paper" viewBox="0 0 1000 500" preserveAspectRatio="none" aria-hidden="true"><path d="M65 4H935Q970 4 994 42V135C951 146 951 171 994 182V359C951 370 951 394 994 405V454L947 494H65Q6 494 6 445V406C49 395 49 371 6 360V182C49 171 49 147 6 136V49Q6 23 65 4Z" fill="#faf0d9" stroke="#073d29" stroke-width="6" vector-effect="non-scaling-stroke"/></svg>';
const paw='<svg viewBox="0 0 30 30" aria-hidden="true"><path fill="currentColor" d="M15 14c-4 0-4 4-7 7-4 5 1 8 5 6 2-1 3-1 5 0 4 2 9-1 5-6-3-3-4-7-8-7Z"/><g fill="currentColor"><ellipse cx="5" cy="12" rx="3" ry="4"/><ellipse cx="12" cy="6" rx="3" ry="4"/><ellipse cx="20" cy="7" rx="3" ry="4"/><ellipse cx="26" cy="14" rx="3" ry="4"/></g></svg>';
function render(){
 document.documentElement.lang=lang;document.title='Scar-Patte · '+c().adminTitle;
 document.querySelector('.language-switch').setAttribute('aria-label',c().language);document.querySelector('.pagination').setAttribute('aria-label',c().pages);
 document.querySelector('h1').textContent=c().adminTitle;document.querySelector('#admin-intro').textContent=c().adminIntro;document.querySelector('#back-link').textContent=c().back;document.querySelector('#refresh').textContent=c().refresh;document.querySelector('#refresh').disabled=loading;
 document.querySelector('#previous').textContent=c().previous;document.querySelector('#next').textContent=c().next;document.querySelector('#previous').disabled=loading||page===0;document.querySelector('#next').disabled=loading||!more;document.querySelector('#page-number').textContent=c().page+' '+(page+1);
 const logout=document.querySelector('[action="/admin/logout"] button');if(logout)logout.textContent=t().logout;
 langButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===lang)));document.querySelector('#admin-feedback').textContent=loading?c().loading:(notice?c()[notice]:'');list.setAttribute('aria-busy',String(loading));list.replaceChildren();
 if(!loading&&!rows.length&&!notice)list.append(el('p',c().empty));
 rows.forEach(r=>{
  const card=el('article',undefined,'request-card booking-ticket');card.innerHTML=paper;
  const stub=el('div',undefined,'booking-stub');stub.setAttribute('aria-hidden','true');stub.innerHTML=paw+'<strong>SCAR<br>PATTE</strong>';stub.append(el('span',t().kindness,'stub-kindness'),el('i',undefined,'booking-barcode'),el('small','SP · 1800'));
  const content=el('div',undefined,'booking-content'),top=el('div',undefined,'request-top'),head=el('div');head.append(el('h2',r.pet_name));head.append(el('p',t().owner+' · '+r.name.replace(' (démo)','')));top.append(head);if(r.is_example)top.append(el('span',t().example,'example-badge'));content.append(top);
  const summary=el('div',undefined,'booking-summary');summary.append(el('span',c().pets[['dog','cat','both'].indexOf(r.pet)],'pet-chip'),el('span',c().services[['bath','trim','care'].indexOf(r.service)],'service-chip'));content.append(summary);
  const dl=el('dl',undefined,'request-details');
  const field=(name,value,kind)=>{const wrap=el('div',undefined,kind==='message'?'request-message':undefined);wrap.append(el('dt',name));const dd=el('dd');if((kind==='email'||kind==='phone')&&!r.is_example){const a=el('a',value);a.href=(kind==='email'?'mailto:':'tel:')+value;dd.append(a)}else dd.textContent=value;wrap.append(dd);dl.append(wrap)};
  field(c().date,new Intl.DateTimeFormat(lang,{dateStyle:'long',timeZone:'Europe/Brussels'}).format(new Date(r.preferred_date+'T12:00:00Z')));field(c().time,c().times[['flexible','morning','afternoon'].indexOf(r.preferred_time)]);field(c().email,r.email,'email');field(c().phone,r.phone,'phone');if(r.message)field(c().message,r.is_example?t()[r.pet==='cat'?'catNote':'dogNote']:r.message,'message');content.append(dl);
  const footer=el('div',undefined,'booking-footer'),label=el('label',undefined,'status-select');label.append(el('span',c().status));const select=el('select');states.forEach((s,i)=>{const o=el('option',c().statuses[i]);o.value=s;select.append(o)});select.value=r.status;
  select.addEventListener('change',async()=>{const old=r.status;select.disabled=true;try{const res=await fetch('/api/admin/requests/'+encodeURIComponent(r.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:select.value})});if(!res.ok)throw Error();r.status=select.value;notice='saveOk'}catch{select.value=old;notice='saveError'}select.disabled=false;document.querySelector('#admin-feedback').textContent=c()[notice]});label.append(select);footer.append(label);content.append(footer,el('p',c().received+' '+new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Brussels'}).format(new Date(r.created_at)),'booking-received'));card.append(stub,content);list.append(card);
 });
}
async function load(){loading=true;notice='';render();try{const res=await fetch('/api/admin/requests?page='+page);if(!res.ok)throw Error();const data=await res.json();rows=data.requests;more=data.hasMore}catch{notice='loadError';rows=[];more=false}finally{loading=false;render()}}
langButtons.forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;try{localStorage.setItem('scar-patte-language',lang)}catch{}render()}));document.querySelector('#refresh').addEventListener('click',load);document.querySelector('#previous').addEventListener('click',()=>{if(page){page--;load()}});document.querySelector('#next').addEventListener('click',()=>{if(more){page++;load()}});load();
