const langButtons=document.querySelectorAll('[data-lang]');let lang='fr',page=0,rows=[],more=false,notice='',loading=false;try{lang=localStorage.getItem('scar-patte-language')||'fr'}catch{}if(!bookingCopy[lang])lang='fr';
const c=()=>bookingCopy[lang];const list=document.querySelector('#request-list');const states=['new','contacted','confirmed','closed'];
function el(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function render(){document.querySelector('.language-switch').setAttribute('aria-label',c().language);document.querySelector('.pagination').setAttribute('aria-label',c().pages);document.documentElement.lang=lang;document.title='Scar-Patte · '+c().adminTitle;document.querySelector('h1').textContent=c().adminTitle;document.querySelector('#admin-intro').textContent=c().adminIntro;document.querySelector('#back-link').textContent=c().back;document.querySelector('#refresh').textContent=c().refresh;document.querySelector('#refresh').disabled=loading;document.querySelector('#previous').textContent=c().previous;document.querySelector('#next').textContent=c().next;document.querySelector('#previous').disabled=loading||page===0;document.querySelector('#next').disabled=loading||!more;document.querySelector('#page-number').textContent=c().page+' '+(page+1);langButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===lang)));document.querySelector('#admin-feedback').textContent=loading?c().loading:(notice?c()[notice]:'');list.replaceChildren();
 if(!loading&&!rows.length&&!notice)list.append(el('p',c().empty));
 rows.forEach(r=>{const card=el('article',undefined,'request-card'),top=el('div',undefined,'request-top'),head=el('div');head.append(el('h2',r.pet_name+' · '+r.name));head.append(el('p',c().received+' '+new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Brussels'}).format(new Date(r.created_at))));top.append(head);const label=el('label',undefined,'status-select');label.append(el('span',c().status));const select=el('select');states.forEach((s,i)=>{const o=el('option',c().statuses[i]);o.value=s;select.append(o)});select.value=r.status;select.addEventListener('change',async()=>{const old=r.status;select.disabled=true;try{const res=await fetch('/api/admin/requests/'+encodeURIComponent(r.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:select.value})});if(!res.ok)throw Error();r.status=select.value;notice='saveOk'}catch{select.value=old;notice='saveError'}select.disabled=false;document.querySelector('#admin-feedback').textContent=c()[notice]});label.append(select);top.append(label);card.append(top);const dl=el('dl',undefined,'request-details');const field=(name,value,kind)=>{const wrap=el('div',undefined,kind==='message'?'request-message':undefined);wrap.append(el('dt',name));const dd=el('dd');if(kind==='email'||kind==='phone'){const a=el('a',value);a.href=(kind==='email'?'mailto:':'tel:')+value;dd.append(a)}else dd.textContent=value;wrap.append(dd);dl.append(wrap)};
 field(c().email,r.email,'email');field(c().phone,r.phone,'phone');field(c().pet,c().pets[['dog','cat','both'].indexOf(r.pet)]);field(c().service,c().services[['bath','trim','care'].indexOf(r.service)]);field(c().date,new Intl.DateTimeFormat(lang,{dateStyle:'long',timeZone:'Europe/Brussels'}).format(new Date(r.preferred_date+'T12:00:00Z')));field(c().time,c().times[['flexible','morning','afternoon'].indexOf(r.preferred_time)]);if(r.message)field(c().message,r.message,'message');card.append(dl);list.append(card)});
}
async function load(){loading=true;notice='';render();try{const res=await fetch('/api/admin/requests?page='+page);if(!res.ok)throw Error();const data=await res.json();rows=data.requests;more=data.hasMore}catch{notice='loadError';rows=[];more=false}finally{loading=false;render()}}
langButtons.forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;try{localStorage.setItem('scar-patte-language',lang)}catch{}render()}));document.querySelector('#refresh').addEventListener('click',load);document.querySelector('#previous').addEventListener('click',()=>{if(page){page--;load()}});document.querySelector('#next').addEventListener('click',()=>{if(more){page++;load()}});load();
